### ISSUE TITLE
npm run build and serve error

### ISSUE THREAD

**Issue by asicfr** [assurance-maladie-digital/vue-cli-preset#7]
Environnement : 
windows 10
node -v  :  v14.18.3
npm -v : 6.14.15

Procedure d'instanciation : 
npm cache clean --force
npm install -g @vue/cli
vue create testvuedot2  --preset assurance-maladie-digital/vue-cli-preset

> Vue CLI v5.0.1
> Failed to check for updates
> ✨  Creating project in C:\DEV\activites\SKVUX\testvuedot2.
> ⚙️  Installing CLI plugins. This might take a while...
> yarn install v1.22.17
> info No lockfile found.
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Saved lockfile.
> Done in 71.28s.
> 🚀  Invoking generators...
> @cnamts/vue-cli-plugin-vue-dash
> ? Description du projet My amazing project
> ? Utiliser Vue i18n pour gérer les textes de l’application Yes
> ? Utiliser Vuex Persist pour persister le store Yes
> ? Utiliser Cypress pour les tests d’interface No
> ? Utiliser la configuration Jenkins par défaut Yes
> ? Utiliser Matomo pour l’analyse d’audience Yes
>  WARN  conflicting versions for project dependency "@vue/cli-service":
>        - ~5.0.0 injected by generator "undefined"
>        - ~4.5.15 injected by generator "@cnamts/vue-cli-plugin-vue-dash"
>        Using newer version (~5.0.0), but this may cause build errors.
>  WARN  conflicting versions for project dependency "sass-loader":
>        - ^12.0.0 injected by generator "@vue/cli-service"
>        - ^10.2.0 injected by generator "@cnamts/vue-cli-plugin-vue-dash"
>        Using newer version (^12.0.0), but this may cause build errors.
> 📦  Installing additional dependencies...
> yarn install v1.22.17
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> info There appears to be trouble with your network connection. Retrying...
> success Saved lockfile.
> Done in 232.91s.
> ⚓  Running completion hooks...
> [4/4] ⠈ deasync
> 🎉  Successfully created project testvuedot2.
> 👉  Get started with the following commands:
>  $ cd testvuedot2
>  $ yarn serve

push sur git

pull depuis git
npm install
npm run build

> testvuedot2@0.1.0 build C:\DEV\activites\SKVUX\testvuedot2
> vue-cli-service build
> **ERROR  Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
>                 currentResource = resource
>                 return true
>               })**
> Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
>         currentResource = resource
>         return true
>       })
>     at RuleSetCompiler.error (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:373:10)
>     at RuleSetCompiler.compileCondition (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:309:17)
>     at C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\BasicMatcherRulePlugin.js:29:40
>     at Hook.eval [as call] (eval at create (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:19:1)
>     at RuleSetCompiler.compileRule (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:177:19)
>     at C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9
>     at Array.map (<anonymous>)
>     at RuleSetCompiler.compileRules (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
>     at RuleSetCompiler.compileRule (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:184:30)
>     at C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9
>     at Array.map (<anonymous>)
>     at RuleSetCompiler.compileRules (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
>     at RuleSetCompiler.compile (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\rules\RuleSetCompiler.js:68:22)
>     at new NormalModuleFactory (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\NormalModuleFactory.js:237:34)
>     at Compiler.createNormalModuleFactory (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:1115:31)
>     at Compiler.newCompilationParams (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\node_modules\webpack\lib\Compiler.js:1136:30)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! testvuedot2@0.1.0 build: `vue-cli-service build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the testvuedot2@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\LABBE-30894\AppData\Roaming\npm-cache\_logs\2022-03-07T15_00_08_496Z-debug.log

npm run serve

> vue-cli-service serve
>  WARN  Fix missing config.js file
> Copied public/js/config.js.dist to public/js/config.js
>  INFO  Starting development server...
>  **ERROR  ValidationError: Progress Plugin Invalid Options**
>         options should NOT have additional properties
>         options should NOT have additional properties
>         options should NOT have additional properties
>         options should pass "instanceof" keyword validation
>         options should match exactly one schema in oneOf
> ValidationError: Progress Plugin Invalid Options
> options should NOT have additional properties
> options should NOT have additional properties
> options should NOT have additional properties
> options should pass "instanceof" keyword validation
> options should match exactly one schema in oneOf
>     at validateOptions (C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack\node_modules\schema-utils\src\validateOptions.js:32:11)
>     at new ProgressPlugin (C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack\lib\ProgressPlugin.js:62:3)
>     at new Progress (C:\DEV\activites\SKVUX\testvuedot2\node_modules\progress-webpack-plugin\index.js:25:21)
>     at new progressPlugin (C:\DEV\activites\SKVUX\testvuedot2\node_modules\progress-webpack-plugin\index.js:127:10)
>     at C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack-chain\src\Plugin.js:14:18
>     at Object.toConfig (C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack-chain\src\Plugin.js:78:22)
>     at C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack-chain\src\Config.js:129:63
>     at Array.map (<anonymous>)
>     at module.exports.toConfig (C:\DEV\activites\SKVUX\testvuedot2\node_modules\webpack-chain\src\Config.js:129:40)
>     at Service.resolveWebpackConfig (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\lib\Service.js:277:34)
>     at PluginAPI.resolveWebpackConfig (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
>     at serve (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\lib\commands\serve.js:73:31)
>     at serve.fn (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@cnamts\vue-cli-plugin-vue-dash\index.js:16:10)
>     at Service.run (C:\DEV\activites\SKVUX\testvuedot2\node_modules\@vue\cli-service\lib\Service.js:262:12)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! testvuedot2@0.1.0 serve: `vue-cli-service serve`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the testvuedot2@0.1.0 serve script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\LABBE-30894\AppData\Roaming\npm-cache\_logs\2022-03-07T15_05_42_231Z-debug.log

Merci d'avance.

Cdl

**Comment by deraw** [comment]
Hello,

Le bug est dû à Vue CLI 5 qui a été publié récemment. En cas de conflit entre plusieurs versions, il prend la dernière :
```
- ~5.0.0 injected by generator "undefined"
- ~4.5.15 injected by generator "@cnamts/vue-cli-plugin-vue-dash"
```

Il faut que l'on mette à jour Vue CLI dans le Starter Kit.

**Comment by deraw** [comment]
Hello,

La mise à jour a été effectuée https://github.com/assurance-maladie-digital/design-system/pull/1913 et le correctif sera publié dans la prochaine version
